<?xml version="1.0" encoding="utf-8"?><Database Name="SMS" Class="SMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\K44B;Initial Catalog=SMS;Integrated Security=True" SettingsObjectName="Student_Manegement_System.Properties.Settings" SettingsPropertyName="SMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="MaAdmin" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenAdmin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Chuongtrinhdaotao" Member="Chuongtrinhdaotaos">
    <Type Name="Chuongtrinhdaotao">
      <Column Name="MaHocPhan" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHocPhan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoTinChi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Chuongtrinhdaotao_LopHocPhan" Member="LopHocPhans" ThisKey="MaHocPhan" OtherKey="MaHocPhan" Type="LopHocPhan" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien" Member="GiangViens">
    <Type Name="GiangVien">
      <Column Name="MaGiangVien" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGiangVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Quequan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sodienthoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GiangVien_LopHocPhan" Member="LopHocPhans" ThisKey="MaGiangVien" OtherKey="MaGiangVien" Type="LopHocPhan" />
    </Type>
  </Table>
  <Table Name="dbo.LopHocPhan" Member="LopHocPhans">
    <Type Name="LopHocPhan">
      <Column Name="ThoiKhoaBieu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MaHocPhan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaGiangVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GiangVien_LopHocPhan" Member="GiangVien" ThisKey="MaGiangVien" OtherKey="MaGiangVien" Type="GiangVien" IsForeignKey="true" />
      <Association Name="Chuongtrinhdaotao_LopHocPhan" Member="Chuongtrinhdaotao" ThisKey="MaHocPhan" OtherKey="MaHocPhan" Type="Chuongtrinhdaotao" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSinhVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSinhVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lop" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Quequan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="MaNguoiDung" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tendangnhap" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.id_giangvien" Method="id_giangvien">
    <ElementType Name="id_giangvienResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.id_hocphan" Method="id_hocphan">
    <ElementType Name="id_hocphanResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.id_lophocphan" Method="id_lophocphan">
    <ElementType Name="id_lophocphanResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.id_nganh" Method="id_nganh">
    <ElementType Name="id_nganhResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.id_taikhoan" Method="id_taikhoan">
    <ElementType Name="id_taikhoanResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.id_sinhvien" Method="id_sinhvien">
    <ElementType Name="id_sinhvienResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>